apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  GITHUB_WEBHOOK_SECRET: "mywebhook_4538641wedf/"
  GITHUB_APP_ID: "4794028"
  GITHUB_APP_PRIVATE_KEY: "|
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAs4XwIl+9cscx1mB3rMMiqFN47+JeanQBclXdE4zAst9KxhUb
    82PAJJFDaqRalk/OvikxVbxRUz2Jz1tADvjp9CS2//XqN4jgllmqvsmS9Jkcd0kq
    k1v1aS34ONbtv9e4qMxhITBrqTfDxv57ph9Yd5CTs6bDbBGlz5eQguiu6VK7MljH
    LxZ+BkxIuPgymr2rbKz6+7o1NdqW4k9+AKpJd5jymhp6LsYfsK9385vN1bJaO4pS
    HV+/SKHArlx4APTPeenKPQjsjBDztU6b7oW69rx9ib7KuhbsIZ5ZrB+RS/grjXOw
    R/MtcVXVioaODt2C+3g7FJsvQZiXALn6k/Y3HQIDAQABAoIBAQCWmLgeDdR98Y3k
    OV6LRdLQA94C1hHAGXqRMGhZmwyXwOsYCeM9pKMtydIVJrR7PY3ARgwF0Qkj3A68
    LN8q8DJKRXZieCe32JIWbjfm/m/R0pNnmbAml9DiH9cHz3z4Hv3gVDryvYzDEm2g
    hCCz9b2f51+QKEftY0yGPa3Ts1/vh7h+EqpmvqI2UU1RlXT7/v12DNvs4H064VpP
    t5ITY3DDIStNfm/pUBLUpvpyQ8Hs9uO9/d50GuZX06dc+10eyMMT9tX7DaY/xPMJ
    1eJzLPZZSJtZHtH80G5sqYClReavFIt595czkn6qcYwIB+mYakStlkkqJ/DJ6SJu
    9m8qS41hAoGBANzSdQlty6ENR/zROEvNYhfvJdJy9/DyT4ZgFnXIWTCo/nJG1e1r
    OcFjI/Z7e0MSqybH9IxIksKn4e2ORGy220Ibp7WYY05Ks19meaRotZHEvI1iIo0i
    rHhuTTdHV1vjSFQyHoco8BG8KmTa7j+6X/4P6r/qfN51azG3Psypy28lAoGBANAf
    O8Uf1nN4hevFw0624FSjBnP3ScBgU7KpUbn49BeSBwv4a7pKo00JtJSII8z6e7Bt
    e3Fhl8GhpeV/Np9wkoKJ2RO1LLAKizH6T/BZ9zZlM+gB06XPZOxwL0L3hjP6vvtH
    e1HejcES8iA4EoWjafFhPIKxJ/339BA1MrbkMIKZAoGAMYYZrXWsV4BNBsw9XfK/
    7zI5P0t9g9I0N6TRJLU8G4erGSH91HNZzp9Xb24eJNrI+7eYhuW31GQmbUqc2ezg
    m6DsKfP1QZfLRrgKy+6X2gtPZj3+Fb0TBSdnteAQHZGJpShgZFuwC6oxr9DR4gUA
    hlA3i7chLhsTYWEBepESCOkCgYEAoYKLlNe3SdcPPsAzaCOdhbEaMeaHUoaujWi+
    5q7fZmdJlq2LlH+VqRROEjJwbgM499qOwJd2+KpknuwRTLxExo8JajTgYCFekkNp
    w+FdatYw6Ox5/iQrcx1AYBzNBguiKEj517f5lAsK4ZwCK7l8XvkRx26J1ZqVyfou
    yCXfy4kCgYBFaxxIop9BPqLWTQ1x5J1PG9sh2IQ8dfNZDm+/2XknjaFywzkKuaVX
    glShamDoj45WZHdD86i0D2qorpQDZ4gAqact0pnhvhGAScjLYs9N8LXpr+1i5Kob
    QBZshQCRYOvFcfqS5qcVNtQ2GxlL+FJo2rrrc6XFpZBt9cBMPiPDxQ==
    -----END RSA PRIVATE KEY-----"
  OPENAI_API_KEY: "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"
  LANGFUSE_PUBLIC_KEY: "pk-lf-507bd72f-a04b-480e-beb5-76c6b9c25883"
  LANGFUSE_SECRET_KEY: "sk-lf-d25da772-65f9-438d-b318-abed07d4b6f1"
  DATABASE_URL: "postgresql+asyncpg://dbadmin:cricket123Rohit@ai-code-reviewer-postgres.c6psyecqicmj.us-east-1.rds.amazonaws.com/codereviewer"

